services:
  frontend:
    build:
      context: ./frontend
    image: frontend-img
    ports:
      - "3200:3200"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
    image: backend-img
    ports:
      - "5020:5020"
